### ISSUE TITLE
LinkML validation issues

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/datalad-concepts#16]
A thread to highlight/discuss LinkML validation issues that we might or might not have workarounds or solutions for.

**Comment by jsheunis** [comment]
### 1. Combined use of `default_range: string` and `any_of`-enabled unions of ranges

If a class's slot is intended to have a union of multiple ranges via the use of `any_of` and the schema has `default_range: string` defined at the top level, `linkml-validate` will throw an error containing `<some-input-data> is not of type 'string'`.

Example schema excerpt:
```yaml
default_range: string

slots:
  children:
    slot_uri: dcterms:hasPart
    multivalued: true
    inlined: true
    inlined_as_list: true
    any_of:
      - range: integer
      - range: Dog
    description: >-
      Children of a Parent can be integers or Dogs

classes:
  Parent:
    tree_root: true
    description: >-
      A parent
    slots:
      - children
    slot_usage:
      children:
        required: true
  Dog:
    tree_root: true
    description: >-
      A dog
    attributes:
      name:
        required: true
        range: string
```
Example data that should be valid:

```yaml
children:
  - name: Bingo
  - 1
```

Validation output:
```
> linkml-validate ...
[ERROR] [src/examples/range-union-schema/Parent-sample.yaml/0] {'name': 'Bingo'} is not of type 'string' in /children/0
[ERROR] [src/examples/range-union-schema/Parent-sample.yaml/0] 1 is not of type 'string' in /children/1
```

Known issues/comments:
- https://github.com/linkml/linkml/issues/1422#issuecomment-1718487180
- https://github.com/linkml/linkml/issues/1483
- https://github.com/linkml/linkml/issues/1272
