### ISSUE TITLE
Incomplete SHACL export of `any_of` range

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/datalad-concepts#179]
I picked this up in [shacl-vue](https://github.com/psychoinformatics-de/shacl-vue/issues/44) and traced it back to the following:

https://github.com/psychoinformatics-de/datalad-concepts/blob/main/src/prov/unreleased.yaml#L165-L177:

```yaml
  influencer:
    slot_uri: dlprov:influencer
    description: >-
      Reference the resource (Entity, Agent, or Activity) whose influence is
      being qualified in a qualified influence pattern.
    any_of:
      - range: Activity
      - range: Agent
      - range: Entity
    exact_mappings:
      - prov:influencer
    broad_mappings:
      - dcterms:relation
```

It looks like the `any_of` range doesn't get propagated correctly to the SHACL export. I need to investigate whether LinkML's `shaclgen` actually deals with this.
