### ISSUE TITLE
Should prefixes in data also be emitted or included in list of schema prefixes?

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/datalad-concepts#250]
I'm busy putting some rdf data together for testing `shacl-vue` and getting an error during conversion of examples:

```
>> make convert-examples

...

Converting src/social/unreleased/examples/Project-03-relations.yaml

ValueError: File "Project-03-relations.yaml", line 6, col 16: Unknown CURIE prefix: dcterms
make: *** [convertexamples/social/unreleased] Error 1
```

This is the data:

```
# a project is an activity, hence can use any of its means to
# declare relationships to other things
id: https://example.com/projects/p1a
characterized_by:
  - object: https://example.com/projects/grand-plan
    predicate: dcterms:isPartOf
associated_with:
  - http://orcid.org/0000-0001-6398-6370
qualified_relations:
  - object: http://orcid.org/0000-0001-6398-6370
    had_roles:
      # contributor
      - marcrel:ctb
```

and the `dlsocial` schema doesn't include or emit the `dcterms` prefix, which seems sensible because the schema couldn't possibly cover all possibilities. So should (YAML) data then rather use an absolute URI?
