### ISSUE TITLE
Allow `string` as value-type in `relations`-slot of `Thing` to store `id`s of extracted records

### ISSUE THREAD

**Issue by christian-monch** [psychoinformatics-de/datalad-concepts#275]
Currently the [dump-thing server](https://github.com/christian-monch/dump-things-server) extraction of records that are inlined via the `relations`-slot in `Thing`.

If inlined records are extracted, their `id`s must be stored in the record from which they were extracted. The current strategy to store the `id`s of extracted records in the `relations`-slot of the record from which they were extracted.

The `relations`-slot is defined to be a dictionary (by setting `multivalued: true`, `inlined: true`, and `inlined_as_list: false`). The key-type of this dictionary is `string` and the value-type is `Thing`. Furthermore, in each key-value pair, the `id` of the value-object has to be identical to the key. Therefore we store a reference to extracted objects as a minimal `Thing`-instance, that is a `Thing` that only contains the `id` of the extracted record.

There are a few problems with this approach

1. The `Thing` instance has the same `id` as a previously extracted record that is in most cases not of the type `Thing`. Now there are two relations:
  - `<id> is_a Thing`
  - `<id> is_a <extracted object type>`
This is probably not false because `<extracted object type>` is a subclass of `Thing`, but it smells unclean.

2. If "empty" `Thing`-instances are used to record extracted objects, they cannot be extracted themselves, although they are stored in `relations`. This make the object-extractor slightly more complex. It also prevents genuine "empty" `Thing`-instances from being extracted. The latter might never occur, but theoretically such an object would never be extracted and stored individually.

This situation should be improved. One possible improvement would be define the slot as `any_of` `string` or `Thing`. This should allow to store either `Thing`-instances or empty strings as value for extracted objects. In the latter case, the key would be used as a reference to an extracted object.

Unfortunately it seems that the use of `any_of` does not work well with inheritance. More precisely if we define the slot `relations` like this (according to the [documentatio](https://linkml.io/linkml/schemas/advanced.html#unions-as-ranges))

```
...

classes:
  Any:
    class_uri: "linkml:Any"

slots:
  relations:
    range: Any
    any_of:
      - range: string
      - range: Thing
    multivalued: true
    inlined: true
    inlined_as_list: false
...
```
and generate pydantic-classes, the only valid entries in the values of the `relations`-dict are `string`  and `Thing`-instance, but **not** instances of subclasses of `Thing`.

To allow relations to all subclasses of `Thing`, all subclasses have to be mentioned explicitly, like this:
```
...

slots:
  relations:
    range: Any
    any_of:
      - range: string
      - range: Thing
      - range: Person
      - range: Agent
      - range: InstantaneousEvent
      - range: Activity
      - range: ValueSpecification
      - range: Role
      - range: Location
      - range: SoftwareAgent
      - range: Entity
      - range: Organization
      - range: Project
      - range: Author
      - range: Interviewer
    multivalued: true
    inlined: true
    inlined_as_list: false
...
```

With this declaration the pydantic validator will allow an instance of any of the given classes as value in `relations`.  This seems weird.

Another strange fact: `linkml-validate` now expects an array as type of `relations`. It seem as if `inlined_as_list` is completely ignored.
