### ISSUE TITLE
Bring back `ExecutableFile` in some form

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-concepts#283]
```yaml
  ExecutableFile:
    class_uri: dldist:ExecutableFile
    is_a: Role
    description: >-
      An executable file is a digital file that executes a process.
    exact_mappings:
      - obo:ONTOAVIDA_00000002
```
