### ISSUE TITLE
Find a way to declare "document-local" "identifiers"

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-concepts#66]
RO-crate uses JSON-LD's relative `@id`s for describing entities that have no globally unique, absolute identifier (e.g., a Person). We need something similar, for similar reasons.

We need to explore what conditions apply to an linkml `identifier:true` slot exactly. Does it need to be a CURIE or better?

> the range of an identifier can be any type, but it is a good idea to have these be of type

If so, maybe we could simply declare a `self` prefix and establish the convention that this is simply not unique.

I am not aware of a mechanism matching JSON-LD's `@base` for completing "relative" identifiers.

**Comment by jsheunis** [comment]
I came across this issue: https://github.com/linkml/linkml/issues/576
And the related PR: https://github.com/linkml/linkml-runtime/pull/223
Specifically this part of the example schema from the test: https://github.com/linkml/linkml-runtime/pull/223/files#diff-ed3638120d93a94a50fae4ed9640aa8b67669494a46ddcdc849bdfab82dcb9bfR13-R22

```yaml
types:
  Code:
    typeof: string
    description: >-
      An identifier that is encoded in a string.  This is used to represent
      identifiers that are not URIs, but are encoded as strings.  For example,
      a person's social security number is an encoded identifier.
    annotations:
      prefix: "@base"
      percent_encoded: true
```

This seemed applicable to our challenge so I started building a local test case to see if it works, using a research dataset with many authors, and many publications which in turn could also have many authors (overlapping with dataset authors). However, I got stuck at errors with uninformative error messages that I'm still trying to debug.

**Comment by jsheunis** [comment]
Here's what I have currently:

Schema:

```yaml
id: https://concepts.datalad.org/schemas/research-dataset
name: research-dataset
title: Research dataset
description: >-
  This schema draft models a generic research dataset for
  the purpose of making it findable and understandable for
  humans, for example via an online data catalog.
prefixes:
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/

imports:
  - linkml:types

# TYPES
types:
  Code:
    typeof: string
    description: >-
      An identifier that is encoded in a string.  This is used to represent
      identifiers that are not URIs, but are encoded as strings.  For example,
      a person's social security number is an encoded identifier.
    annotations:
      prefix: "@base"
      percent_encoded: true

# SLOTS
slots:
  author:
    slot_uri: schema:author
    multivalued: true
    inlined_as_list: true
    range: Author
    description: >-
      A list of authors of an entity
  citation:
    slot_uri: schema:citation
    range: string
    description: >-
      A text-based citation providing information about a
      publication, dataset, or creative work
  date_modified:
    slot_uri: schema:dateModified
    range: date
    description: >-
      Date of the last modification of a described dataset
      (version), for example a release date. Must be given
      in ISO 8601 format (YYYY-MM-DD).
  date_published:
    slot_uri: schema:datePublished
    range: date
    description: >-
      The date on which the work was published. Must be given
      in ISO 8601 format (i.e., YYYY-MM-DD).
  description:
    slot_uri: schema:description
    range: string
    description: >-
      A general description of an entity
  doi:
    slot_uri: bibo:doi
    range: string
    description: >-
      The Digital Object Identifier of an entity, see:
      https://www.doi.org/the-identifier/what-is-a-doi
  email:
    slot_uri: schema:email
    description: >-
      An email address of an entity
  id:
    slot_uri: schema:identifier
    range: Code
    identifier: true
    description: >-
      The name or code that uniquely identifies an entity
  name:
    slot_uri: schema:name
    range: string
    description: >-
      The name of an entity
  publication:
    slot_uri: schema:publication
    multivalued: true
    inlined_as_list: true
    range: Publication
    description: >-
      A list of publications (articles, books, software, etc.)
      associated with a dataset.
  title:
    slot_uri: schema:title
    range: string
    description: >-
      A text title that serves as the human-readable heading
      of an entity. This is distinct from 'name', which could
      (but does not necessarily have to) be human-readable.
  url:
    slot_uri: schema:url
    range: string
    description: >-
      An online location where an entity can be accessed.


# CLASSES
classes:

  Container:
    tree_root: true
    attributes:
      dataset:
        multivalued: false
        range: ResearchDataset
        inlined: true
      authors:
        multivalued: true
        range: Author
        inlined: true
        inlined_as_list: true
      publications:
        multivalued: true
        range: Publication
        inlined: true
        inlined_as_list: true

  ResearchDataset:
    slots:
      - author
      - description
      - name
      - publication
      - title
  
  Author:
    slots:
      - email
      - name
      - id
  
  Publication:
    slots:
      - url
      - author
      - citation
      - doi
      - date_published
      - id
```

Data:

```yaml
authors:
  - id: ahorst@ucsb.edu
    email: ahorst@ucsb.edu
    name: Allison Horst
  - id: b@example.com
    email: b@example.com
    name: Alison Hill
  - id: c@example.com
    email: c@example.com
    name: Kristen Gorman
publications:
  - id: https://doi.org/10.1371/journal.pone.0090081
    doi: https://doi.org/10.1371/journal.pone.0090081
    author:
      - c@example.com
    citation: 'Gorman KB, Williams TD, Fraser WR (2014) Ecological Sexual Dimorphism
      and Environmental Variability within a Community of Antarctic Penguins (Genus
      Pygoscelis). PLoS ONE 9(3): e90081.'
    date_published: '2014-03-05'
dataset:
  name: penguins
  title: Palmer Penguins
  description: The goal of palmerpenguins is to provide a great dataset for data exploration
    and visualization, as an alternative to iris. Data were collected and made available
    by Dr. Kristen Gorman and the Palmer Station, Antarctica LTER, a member of the Long
    Term Ecological Research Network.
  author:
    - ahorst@ucsb.edu
    - b@example.com
    - c@example.com
  publication:
    - https://doi.org/10.1371/journal.pone.0090081
```

But I'm getting these validation errors:

```
> linkml-validate -s src/linkml/schemas/research-dataset.yaml src/examples/research-dataset/research_dataset_data.yaml

[ERROR] [src/examples/research-dataset/research_dataset_data.yaml/0] 'ahorst@ucsb.edu' is not of type 'object' in /dataset/author/0
[ERROR] [src/examples/research-dataset/research_dataset_data.yaml/0] 'b@example.com' is not of type 'object' in /dataset/author/1
[ERROR] [src/examples/research-dataset/research_dataset_data.yaml/0] 'c@example.com' is not of type 'object' in /dataset/author/2
[ERROR] [src/examples/research-dataset/research_dataset_data.yaml/0] 'https://doi.org/10.1371/journal.pone.0090081' is not of type 'object' in /dataset/publication/0
[ERROR] [src/examples/research-dataset/research_dataset_data.yaml/0] 'c@example.com' is not of type 'object' in /publications/0/author/0
```
