### ISSUE TITLE
Flip ontology and schema class naming?

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-concepts#67]
The purpose of these classes is that schema classes **add** specification on data **structure** to concept classes -- for a particular schema.

This means that any type information ending up on data recorded (for example for type designator slots) will reference schema element classes (so something like `DatasetSE`).

This is not nice, because it indicates that this is a somehow special dataset.

We should consider have a schema use simple class names for schema elements, and the ontology classes have a suffix.

Those ontology classes are already mixins, so that could be a sensible suffix. However, in the schema this is somewhat redundant:

```yaml
classes:
  Demo:
    mixins:
      - DemoMixin
``` 

Alternative ideas:

```yaml
classes:
  Demo:
    mixins:
      - DemoConcept
      - DemoOC # (Ontology Class/Concept)
      - DemoS # (Semantics; might actually read nice, like a plural S)
      - DemoRD # (borrowed from (RD)F: resource description. Nice analogy to RDF-S also
```
